spring.cloud.stream:
  bindings:
    output: // Имя канала.
      destination: Messages /*
                              Получение доступа к org.springframework.cloud.stream.config.BindingProperties и настройка
                              имени получателя в брокере сообщений.
                            */
      producer: // Настройка поведения производителя.
        requiredGroups: statistic, ui /*
                                        Настройка списка получателей, которые должны получать сообщения с гарантией 
                                        доставки хотябы один раз.
                                      */

spring.cloud.stream:
  bindings:
    input: // Определение ввода input, описывает конфигурацию потребителя.
      destination: Messages
      group: statistic // Определение имени group. Представляет имя группы получателей в брокере сообщений.
    output:
      producer:
        requiredGroups: ui
      destination: Statistic

spring.cloud.stream:
  bindings:
    statistic:
      destination: Statistic
      group: ui
    messages:
      destination: Messages
      group: ui
